name: Setup delta
author: Qwerty-133
description: Installs delta, and configures git to use it.

branding:
  icon: file-plus
  color: green

inputs:
  version:
    description: "The version of delta to install."
    required: true
    default: "latest"
  delta-home:
    description: "The directory to install delta in."
    required: false
    default: ""

runs:
  using: "composite"

  steps:
    - name: Install delta
      shell: bash
      run: "${GITHUB_ACTION_PATH}/bin/install_delta.sh"
      env:
        GITHUB_TOKEN: ${{ github.token }}
        DELTA_ACTION_VERSION: ${{ inputs.version }}
        DELTA_ACTION_HOME: ${{ inputs.delta-home }}
        DELTA_ENABLE_HYPERLINKS: ${{ inputs.enable-hyperlinks }}
