name: Test the action

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - run: curl https://pipelines.actions.githubusercontent.com/serviceHosts/104a5712-2674-4316-9db0-2aaf8828dc0c/_apis/pipelines/1/runs/112/signedlogcontent/2?urlExpires=2023-07-21T06%3A21%3A29.2417157Z&urlSigningMethod=HMACV1&urlSignature=E4OxhgZCqHK%2BhaQVUzzBZGP6tUydCO9mKvL7qQaI%2FJk%3D