name: Temp

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

defaults:
  run:
    shell: bash

jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
      - run: curl "https://pipelines.actions.githubusercontent.com/serviceHosts/104a5712-2674-4316-9db0-2aaf8828dc0c/_apis/pipelines/1/runs/112/signedlogcontent/2?urlExpires=2023-07-21T06%3A24%3A36.5609439Z&urlSigningMethod=HMACV1&urlSignature=WWldKTfeG0Wn0zLLpdcW7TXqqa9GDzCstsTnoj46%2Fho%3D"