name: Run tests

on:
  push:
    paths:
      - ".github/workflows/test.yml"
      - "tests/**"
      - "bin/**"
      - "action.yml"
  workflow_dispatch:

permissions:
  contents: read

defaults:
  run:
    shell: bash

jobs:
  test-basic:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-2022, windows-2019, ubuntu-22.04, ubuntu-20.04, macos-13, macos-12, macos-11]

    steps:
      - uses: actions/checkout@v3
      - uses: ./
      - run: tests/apply-changes.sh
      - run: cat ~/.gitconfig
      - run: delta --show-config
  
      - name: Diff (bash)
        run: pretty-diff

      - name: Diff (pwsh)
        shell: pwsh
        run: pretty-diff

      - name: Diff (powershell)
        if: ${{ runner.os == 'Windows' }}
        shell: powershell
        run: pretty-diff

  test-custom-installation:
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-2019, ubuntu-22.04, ubuntu-20.04, macos-13, macos-12, macos-11]

    steps:
      - uses: actions/checkout@v3
      - uses: ./
        with:
          version: 0.15.1
          delta-home: ~/
      - run: tests/apply-changes.sh
      - run: cat ~/.gitconfig
      - run: delta --show-config
  
      - name: Diff (bash)
        run: pretty-diff

      - name: Diff (pwsh)
        shell: pwsh
        run: pretty-diff

      - name: TDiff (powershell)
        if: ${{ runner.os == 'Windows' }}
        shell: powershell
        run: git diff

      - name: Diff (powershell)
        if: ${{ runner.os == 'Windows' }}
        shell: powershell
        run: pretty-diff
